README.md
package.json
src/api/providers/__tests__/openrouter.test.ts

Rename project to Hataraku and update documentation

---

.github/workflows/release.yml

fix: improve release workflow to handle existing tags

---

.github/workflows/release.yml

This PR improves the release workflow by:
1. Properly handling branch names with timestamps
2. Using GitHub outputs for sharing values between steps
3. Improving error handling for existing tags
4. Better PR description for release changes
After merging this PR, we can use the improved release workflow to create new releases.

fix: improve release workflow

---

.changeset/shaggy-zebras-ring.md
.github/workflows/release.yml

This PR improves the release workflow with:
1. Better Git Configuration
- Using proper GitHub Actions bot identity
- Better commit messages with version numbers
2. Changelog Management
- Automatically updating CHANGELOG.md
- Including release date
- Maintaining a consistent format
3. Enhanced PR Creation
- More descriptive PR titles with version numbers
- Structured PR description with clear sections
- Better documentation of what happens after merge
4. Workflow Improvements
- Added proper GitHub permissions
- Better version tracking using workflow outputs
- Cleaner branch naming

feat: improve release workflow

---

.github/workflows/changeset-release.yml
.github/workflows/code-qa.yml

Implements changesets for automated version management and release workflow

feat: implement changesets

---

.github/workflows/changeset-release.yml
.github/workflows/code-qa.yml

Improves and streamlines the installation process

fix: improve installation process

---

.github/workflows/changeset-release.yml

Updates GitHub Actions secrets

fix: update gha secrets

---

package.json

Updates GitHub Actions changeset version

fix: update gha changeset version

---

docs/sdk-proposal.md

small changes to proposal

---

docs/sdk-proposal.md

This PR updates the documentation.

updated docs

---

src/cli.ts
src/core/TaskHistory.ts
src/core/assistant-message/index.ts
src/core/prompts/tools/attempt-completion.ts
src/core/prompts/tools/fetch.ts
src/core/prompts/tools/index.ts
src/core/prompts/tools/play-audio.ts
src/core/prompts/tools/show-image.ts
src/core/prompts/tools/to-graph.ts
src/core/prompts/tools/wait-for-user.ts
src/core/task-loop.ts
src/lib/mcp/McpClient.ts
src/lib/tools/access-mcp-resource.ts
src/lib/tools/attempt-completion.ts
src/lib/tools/browser-action.ts
src/lib/tools/execute-command.ts
src/lib/tools/fetch.ts
src/lib/tools/index.ts
src/lib/tools/list-code-definition-names.ts
src/lib/tools/list-files.ts
src/lib/tools/play-audio.ts
src/lib/tools/read-file.ts
src/lib/tools/search-files.ts
src/lib/tools/show-image.ts
src/lib/tools/to-graph.ts
src/lib/tools/use-mcp-tool.ts
src/lib/tools/wait-for-user.ts
src/lib/tools/write-to-file.ts
src/lib/types.ts
src/services/mcp/McpHub.ts

Please review the changes from feature/test-branch

Feature: Test Branch Changes

---

src/cli.ts

Closes #41
This PR adds a self-update feature to Hataraku via a new --update flag.
- Added --update flag to CLI options
- Implemented update logic using npm install -g
- Added proper error handling with helpful messages (including sudo hint)
- Updated help documentation with the new flag
The feature has been tested and works as expected:
- Running 'hataraku --update' successfully updates to the latest version
- Proper feedback is shown during the update process
- Help text correctly displays the new option
- Error handling works correctly
Users can now update Hataraku by running:
```bash
hataraku --update
```

feat: add --update flag to allow self-updating Hataraku

---

src/core/agent/__tests__/agent.test.ts
src/core/agent/agent.ts
src/core/agent/schemas/config.ts
src/core/agent/types/config.ts
src/examples/schema-validation.ts
src/examples/simple-task.ts
src/examples/streaming-task.ts
src/examples/thread-reuse.ts
src/lib/testing/MockProvider.ts
src/lib/testing/MockTool.ts
src/lib/types.ts

https://helloextend.atlassian.net/browse/DX-3318

fix: [DX-3318] Tool System Implementation

---

.cursor/rules/test.mdc
package-lock.json
package.json
src/lib/types.ts
src/utils/__tests__/xml-stream-processor.test.ts
src/utils/stream-processor.ts
src/utils/xml-stream-processor.ts

refactor: [DX-3318] Tool System Implementation

---

.changeset/forty-carrots-pretend.md

This PR adds a changeset to trigger the automated release process.

Add changeset for patch release

---

.github/workflows/changeset-release.yml

Simplifies the changeset workflow to match the official example from changesets/action, making it more maintainable and reliable.

chore: simplify changeset workflow

---

.changeset/thick-news-joke.md
tsconfig.cjs.json

- Fixed TypeScript declaration generation by enabling declaration output in tsconfig.cjs.json\n- Bumped version to 0.5.1

fix: generate typescript declarations correctly

---

.changeset/few-dryers-shake.md
src/core/agent.ts
src/core/task.ts

change agent and task to make model optional

---

.changeset/rare-pumpkins-reflect.md
docs/configuration.md
src/__tests__/config/AgentManager.test.ts
src/cli/commands/config.ts
src/cli/commands/profile.ts
src/cli/commands/task.ts
src/cli/index.ts
src/config/ConfigLoader.ts
src/config/TaskManager.ts
src/config/__tests__/ConfigLoader.test.ts
src/config/__tests__/FirstRunManager.test.ts
src/config/__tests__/TaskManager.test.ts
src/config/agent-config.ts
src/config/agent-manager.ts
src/config/first-run-manager.ts
src/config/index.ts

fixed some things

---

.changeset/empty-cups-poke.md

add changeset

---

README.md
docs/glow-guide.md
docs/knowledge-base.md
docs/providers.md
examples/knowledge-base.ts
package-lock.json
package.json
src/__tests__/cli.test.ts
src/cli/commands/profile.ts
src/cli/execution.ts
src/cli/index.ts
src/config/ConfigLoader.ts
src/config/profileConfig.ts
src/core/providers/knowledge-base.ts

created a knowledgge base provider that gives hataraku the ability to access custom knowledge bases

feat: [ARCH-1290]  create a knowledge base provider for hatraku
